spring.application.name=yazlab2-1

spring.mongodb.uri=mongodb://localhost:27017/kocaeli_haber_db

# Harita Konfigürasyonu
# OpenStreetMap + Leaflet.js + Nominatim (Ücretsiz Geocoding)
# API Key gerek yok! Tamamen ücretsiz!
map.center.latitude=40.7671
map.center.longitude=29.9427
map.default.zoom=10

# Nominatim Geocoding (Ücretsiz OpenStreetMap Geocoding API)
nominatim.api.url=https://nominatim.openstreetmap.org



