spring.application.name=yazlab2-1

spring.mongodb.uri=mongodb://localhost:27017/kocaeli_haber_db

map.center.latitude=40.7671
map.center.longitude=29.9427
map.default.zoom=10


google.maps.api.key=${GOOGLE_MAPS_API_KEY:}
google.geocoding.api-key=${GOOGLE_GEOCODING_API_KEY:}






